# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x1a\x1bgoogle/protobuf/empty.proto\"%\n\x10UserLoginRequest\x12\x11\n\tuser_name\x18\x01 \x01(\t\"]\n\x11OperationResponse\x12\x12\n\nis_success\x18\x01 \x01(\x08\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\x12\n\nip_address\x18\x03 \x01(\t\x12\x13\n\x0bport_number\x18\x04 \x01(\x05\";\n\x15UserConnectionRequest\x12\x11\n\tuser_name\x18\x01 \x01(\t\x12\x0f\n\x07\x63hat_id\x18\x02 \x01(\t\"=\n\x12\x43hatMessageRequest\x12\x11\n\tfrom_user\x18\x01 \x01(\t\x12\x14\n\x0c\x63hat_message\x18\x02 \x01(\t\"$\n\x11GroupSubscription\x12\x0f\n\x07\x63hat_id\x18\x01 \x01(\t2\xba\x03\n\x0e\x43hatOperations\x12\x34\n\tUserLogin\x12\x11.UserLoginRequest\x1a\x12.OperationResponse\"\x00\x12;\n\x0b\x43onnectUser\x12\x16.UserConnectionRequest\x1a\x12.OperationResponse\"\x00\x12>\n\x0e\x44isconnectUser\x12\x16.UserConnectionRequest\x1a\x12.OperationResponse\"\x00\x12>\n\nDisconnect\x12\x16.UserConnectionRequest\x1a\x16.google.protobuf.Empty\"\x00\x12<\n\x10SubscribeToGroup\x12\x12.GroupSubscription\x1a\x12.OperationResponse\"\x00\x12=\n\x10SendGroupMessage\x12\x13.ChatMessageRequest\x1a\x12.OperationResponse\"\x00\x12\x38\n\rDiscoverUsers\x12\x11.UserLoginRequest\x1a\x12.OperationResponse\"\x00\x32S\n\x10\x43lientOperations\x12?\n\x12ReceiveChatMessage\x12\x13.ChatMessageRequest\x1a\x12.OperationResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERLOGINREQUEST']._serialized_start=43
  _globals['_USERLOGINREQUEST']._serialized_end=80
  _globals['_OPERATIONRESPONSE']._serialized_start=82
  _globals['_OPERATIONRESPONSE']._serialized_end=175
  _globals['_USERCONNECTIONREQUEST']._serialized_start=177
  _globals['_USERCONNECTIONREQUEST']._serialized_end=236
  _globals['_CHATMESSAGEREQUEST']._serialized_start=238
  _globals['_CHATMESSAGEREQUEST']._serialized_end=299
  _globals['_GROUPSUBSCRIPTION']._serialized_start=301
  _globals['_GROUPSUBSCRIPTION']._serialized_end=337
  _globals['_CHATOPERATIONS']._serialized_start=340
  _globals['_CHATOPERATIONS']._serialized_end=782
  _globals['_CLIENTOPERATIONS']._serialized_start=784
  _globals['_CLIENTOPERATIONS']._serialized_end=867
# @@protoc_insertion_point(module_scope)
